from NXOpen import NXObject


class DisplayableObject(NXObject):
    # AttributeInformation
    # AttributeType
    # Blank
    # Color
    # ComputationalTime
    # CreateAttributeIterator
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteUserAttribute
    # DeleteUserAttributes
    # FindObject
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # Highlight
    # IsBlanked
    # IsOccurrence
    # JournalIdentifier
    # Layer
    # LineFont
    # LineWidth
    # Name
    # NameLocation
    # Null
    # ObjectFont
    # ObjectWidth
    # OwningComponent
    # OwningPart
    # Print
    # Prototype
    # RedisplayObject
    # RemoveViewDependency
    # SetAttribute
    # SetBooleanUserAttribute
    # SetName
    # SetNameLocation
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # Tag
    # Unblank
    # Unhighlight
    pass

