# NXOpen
# AttributeTemplatesBuilderAccessKeyMemberType
# AttributeTemplatesBuilderConstraintOptions
# AttributeTemplatesBuilderConstraintOptionsMemberType
# AttributeTemplatesBuilderDefaultBooleanOptions
# AttributeTemplatesBuilderDefaultBooleanOptionsMemberType
# AttributeTemplatesBuilderTemplatesOptions
# AttributeTemplatesBuilderTemplatesOptionsMemberType
# AutomaticTraceline
# AutomaticTracelineModeOption
# AutomaticTracelineModeOptionMemberType
# Axis
# AxisCollection
# AxisOrientation
# AxisOrientationMemberType
# AxisTypes
# AxisTypesMemberType
# BaseCreator
# BaseCreatorExportDestinationOption
# BaseCreatorExportDestinationOptionMemberType
# BaseImporter
# BaseImporterMode
# BaseImporterModeMemberType
# BasePart
# BasePartBookmarkOption
# BasePartBookmarkOptionMemberType
# BasePartCloseAfterSave
# BasePartCloseAfterSaveMemberType
# BasePartCloseModified
# BasePartCloseModifiedMemberType
# BasePartCloseWholeTree
# BasePartCloseWholeTreeMemberType
# BasePartCollaborativeContentType
# BasePartCollaborativeContentTypeMemberType
# BasePartHistoryEventInformation_Struct
# BasePartIncompleteStatus_Struct
# BasePartPartPreview
# BasePartPartPreviewMemberType
# BasePartSaveComponents
# BasePartSaveComponentsMemberType
# BasePartTransientStatus_Struct
# BasePartUnits
# BasePartUnitsMemberType
# BasePropertyTable
# BasePropertyTableBasePropertyType
# BasePropertyTableBasePropertyTypeMemberType
# BaseSession
# BasicEffectivityBuilder
# BlockStylerDebugSession
# Body
# BodyCollection
# BodyDumbRule
# BodyFacetsRule
# BodyFeatureRule
# BodyGroupRule
# BodyList
# BorderLineStyleT
# BorderLineStyleTMemberType
# BrushFacetsRule
# Builder
# BunchFacetsOnFaceRule
# CDF
# CGMBuilder
# CGMBuilderActionOption
# CGMBuilderActionOptionMemberType
# CGMBuilderColor
# CGMBuilderColorMemberType
# CGMBuilderImageResolutionOption
# CGMBuilderImageResolutionOptionMemberType
# CGMBuilderMultipleOption
# CGMBuilderMultipleOptionMemberType
# CGMBuilderOutputTextOption
# CGMBuilderOutputTextOptionMemberType
# CGMBuilderRelationOption
# CGMBuilderRelationOptionMemberType
# CGMBuilderSizeOption
# CGMBuilderSizeOptionMemberType
# CGMBuilderUnitsOption
# CGMBuilderUnitsOptionMemberType
# CGMBuilderVdc
# CGMBuilderVdcMemberType
# CGMBuilderWidth
# CGMBuilderWidthMemberType
# CGMImporter
# CaeObjectType
# CaeObjectTypeCaeSubType
# CaeObjectTypeCaeSubTypeMemberType
# CaeTemplateTestManager
# CaeUITemplateTestManager
# CallbackTestMaskTriple_Struct
# CallbackTestStruct1_Struct
# CallbackTestStruct2_Struct
# CallbackTestStruct3_Struct
# CallbackTestStruct4_Struct
# CamTemplateTestManager
# CamUITemplateTestManager
# CartesianCoordinateSystem
# Catiav4Creator
# Catiav4CreatorSolidBodyOutputOption
# Catiav4CreatorSolidBodyOutputOptionMemberType
# Catiav4Importer
# Catiav5Creator
# Catiav5CreatorExportFromOption
# Catiav5CreatorExportFromOptionMemberType
# Catiav5Importer
# Catiav5ImporterImportToOption
# Catiav5ImporterImportToOptionMemberType
# ClipboardOperationsManager
# CmmInspectTemplateTestManager
# CmmInspectUITemplateTestManager
# CollaborativeContentManager
# CollaborativeDesign
# CollaborativeDesignCollection
# ColorDefinition
# ColorDefinitionRgb
# ColorManager
# ColorRegionRule
# ColorWidth
# Conic
# ContentDefinition
# ContentDefinitionType
# ContentDefinitionTypeMemberType
# ConvergentFacet
# ConvertToFromReferenceBuilder
# ConvertToFromReferenceBuilderOutputType
# ConvertToFromReferenceBuilderOutputTypeMemberType
# CoordinateSystem
# CoordinateSystemCollection
# Creator3MF
# Curve
# CurveChainRule
# CurveCollection
# CurveDumbRule
# CurveFeatureChainRule
# CurveFeatureRule
# CurveFeatureTangentRule
# CurveGroupRule
# CurveParameterType
# CurveParameterTypeMemberType
# CurveSnapOptionsBuilder
# CurveTangentRule
# CustomPopupMenu
# CustomPopupMenuHandler
# CustomPopupMenuItem
# CustomWidth
# CutView
# CutViewCollection
# CylindricalCoordinateSystem
# DataContainer
# DateBuilder
# DateItemBuilder
# DateItemBuilderDayOfMonth
# DateItemBuilderDayOfMonthMemberType
# DateItemBuilderList
# DateItemBuilderMonthOfYear
# DateItemBuilderMonthOfYearMemberType
# DatumAxis
# DatumCollection
# DatumConstraint
# DatumConstraintCurveOption
# DatumConstraintCurveOptionMemberType
# DatumConstraintSolution
# DatumConstraintSolutionMemberType
# DatumConstraintType
# DatumConstraintTypeMemberType
# DatumPlane
# DebugUI
# DebugUIValidationPolicy
# DebugUIValidationPolicyMemberType
# Decal
# DexBuilder
# DexManager
# Direction
# DirectionCollection
# DirectionOnCurveOption
# DirectionOnCurveOptionMemberType
# DirectionOnFaceOption
# DirectionOnFaceOptionMemberType
# DisplayManager
# DisplayManagerFacetCacheMemoryLevelType
# DisplayManagerFacetCacheMemoryLevelTypeMemberType
# DisplayManagerJ3dColor_Struct
# DisplayManagerJ3dData_Struct
# DisplayManagerJ3dMaterial_Struct
# DisplayManagerLayerSetting
# DisplayManagerLayerSettingMemberType
# DisplayManagerShowHideScope
# DisplayManagerShowHideScopeMemberType
# DisplayManagerShowHideType
# DisplayManagerShowHideTypeMemberType
# DisplayModification
# DisplayPartOption
# DisplayPartOptionMemberType
# DisplayableObject
# DisplayableObjectObjectFont
# DisplayableObjectObjectFontMemberType
# DisplayableObjectObjectWidth
# DisplayableObjectObjectWidthMemberType
# DraftPointDataCollection
# DraftTemplateTestManager
# DraftTemplateTestManagerViewConversionType
# DraftTemplateTestManagerViewConversionTypeMemberType
# DraftTemplateTestManagerViewFilter
# DraftTemplateTestManagerViewFilterMemberType
# DraftUITemplateTestManager
# DraftingManager
# DrawingCompareManager
# DrawingUtils
# DxfdwgCreator
# DxfdwgCreatorAutoCADRevisionOptions
# DxfdwgCreatorAutoCADRevisionOptionsMemberType
# DxfdwgCreatorExportAsOption
# DxfdwgCreatorExportAsOptionMemberType
# DxfdwgCreatorExportDataOption
# DxfdwgCreatorExportDataOptionMemberType
# DxfdwgCreatorExportFacesAsOptions
# DxfdwgCreatorExportFacesAsOptionsMemberType
# DxfdwgCreatorExportFromOption
# DxfdwgCreatorExportFromOptionMemberType
# DxfdwgCreatorExportScaleOptions
# DxfdwgCreatorExportScaleOptionsMemberType
# DxfdwgCreatorExportSplinesAsOptions
# DxfdwgCreatorExportSplinesAsOptionsMemberType
# DxfdwgCreatorOutputFileTypeOption
# DxfdwgCreatorOutputFileTypeOptionMemberType
# DxfdwgCreatorOutputToOption
# DxfdwgCreatorOutputToOptionMemberType
# DxfdwgCreatorWidthfactorMethodOptions
# DxfdwgCreatorWidthfactorMethodOptionsMemberType
# DxfdwgImporter
# DxfdwgImporterAspectRatioOptions
# DxfdwgImporterAspectRatioOptionsMemberType
# DxfdwgImporterConvLayoutsAs
# DxfdwgImporterConvLayoutsAsMemberType
# DxfdwgImporterFacetImportAs
# DxfdwgImporterFacetImportAsMemberType
# DxfdwgImporterImportBlocksAs
# DxfdwgImporterImportBlocksAsMemberType
# DxfdwgImporterImportCurvesAs
# DxfdwgImporterImportCurvesAsMemberType
# DxfdwgImporterImportDimensionsAs
# DxfdwgImporterImportDimensionsAsMemberType
# DxfdwgImporterImportPolylinesAs
# DxfdwgImporterImportPolylinesAsMemberType
# DxfdwgImporterImportToEnum
# DxfdwgImporterImportToEnumMemberType
# DxfdwgImporterProcessingOrderAs
# DxfdwgImporterProcessingOrderAsMemberType
# DxfdwgImporterSendLayoutsAs
# DxfdwgImporterSendLayoutsAsMemberType
# DxfdwgImporterSendModelDataAs
# DxfdwgImporterSendModelDataAsMemberType
# DxfdwgImporterUnitsEnum
# DxfdwgImporterUnitsEnumMemberType
# DxfdwgImporterWorkflowAs
# DxfdwgImporterWorkflowAsMemberType
# Edge
# EdgeBodyRule
# EdgeBoundaryRule
# EdgeChainRule
# EdgeDumbRule
# EdgeEdgeType
# EdgeEdgeTypeMemberType
# EdgeFaceRule
# EdgeFeatureRule
# EdgeIntersectRule
# EdgeMultipleSeedTangentRule
# EdgeSheetBoundaryRule
# EdgeTangentRule
# EdgeVertexRule
# EdgeVertexTangentRule
# EffectivityConditionBuilder
# EffectivityConditionBuilderEffectivityConditionType
# EffectivityConditionBuilderEffectivityConditionTypeMemberType
# EffectivityConditionBuilderToUnitType
# EffectivityConditionBuilderToUnitTypeMemberType
# Ellipse
# EllipseCollection
# EndCutBlockBuilder
# EndCutBlockBuilderTaperTypeOption
# EndCutBlockBuilderTaperTypeOptionMemberType
# EngineeringFunction
# ErrorInfo
# ErrorList
# ExcelFileFormatT
# ExcelFileFormatTMemberType
# Expression
# ExpressionCollection
# ExpressionCollectionExportMode
# ExpressionCollectionExportModeMemberType
# ExpressionCollectionImportMode
# ExpressionCollectionImportModeMemberType
# ExpressionCollectionSortType
# ExpressionCollectionSortTypeMemberType
# ExpressionCollectionType
# ExpressionCollectionTypeMemberType
# ExpressionCollectorSet
# ExpressionCollectorSetList
# ExpressionGroup
# ExpressionGroupCollection
# ExpressionSectionSet
# ExpressionSectionSetList
# ExpressionStatusOption
# ExpressionStatusOptionMemberType
# ExpressionUnitsOption
# ExpressionUnitsOptionMemberType
# ExternalFileReference
# ExternalFileReferenceAdapter
# ExternalFileReferenceAdapterType
# ExternalFileReferenceAdapterTypeMemberType
# ExternalFileReferenceManager
# ExternalFileReferenceStatus
# ExternalFileReferenceStatusMemberType
# ExtrudeLimitDataLimitType
# ExtrudeLimitDataLimitTypeMemberType
# ExtrudeOffsetDataOffsetType
# ExtrudeOffsetDataOffsetTypeMemberType
# ExtrudeTaperDataTaperType
# ExtrudeTaperDataTaperTypeMemberType
# Face
# FaceAdjacentRule
# FaceAllBlendRule
# FaceAndAdjacentFacesRule
# FaceBodyRule
# FaceBossPocketFacesRule
# FaceChamferType
# FaceChamferTypeMemberType
# FaceConnectedBlendRule
# FaceDumbRule
# FaceFaceType
# FaceFaceTypeMemberType
# FaceFacetsRule
# FaceFeatureRule
# FaceMergedRibFacesRule
# FaceRegionBoundaryRule
# FaceRegionRule
# FaceRibFacesRule
# FaceSlotFacesRule
# FaceTangentRule
# FacetCollector
# FacetCollectorCollection
# FacetSelectionRule
# FacetSelectionRuleFactory
# FeatureGeneralPropertiesBuilder
# FeatureIntersectionEdgesRule
# FeaturePointsRule
# FeatureProcessBuilderStatus
# FeatureProcessBuilderStatusResultStatus
# FeatureProcessBuilderStatusResultStatusMemberType
# FfmTemplateTestManager
# FfmUITemplateTestManager
# FileNew
# FileNewApplication
# FileNewApplicationMemberType
# FileNewTemplate
# FileNewTemplateType
# FileNewTemplateTypeMemberType
# FillBoundaryRule
# FineBrushFacetsRule
# FlatteningBuilder
# FlatteningBuilderDistortionMapType
# FlatteningBuilderDistortionMapTypeMemberType
# FlatteningBuilderFlatteningConstantType
# FlatteningBuilderFlatteningConstantTypeMemberType
# FlatteningBuilderTypes
# FlatteningBuilderTypesMemberType
# FloodFillFacetsRule
# FollowFilletRule
# FollowFilletRuleType
# FollowFilletRuleTypeMemberType
# FontCollection
# FontCollectionType
# FontCollectionTypeMemberType
# FourPointSurfaceBuilder
# GeneralScalarTable
# GenericMeasure
# GenericMeasureType
# GenericMeasureTypeMemberType
# Group
# GroupBuilder
# GroupBuilderAction
# GroupBuilderActionMemberType
# GroupBuilderSketchType
# GroupBuilderSketchTypeMemberType
# GroupBuilderUngroupOption
# GroupBuilderUngroupOptionMemberType
# HumanData
# HumanDataAdvancedScalingType
# HumanDataAdvancedScalingTypeMemberType
# HumanDataAppearanceType
# HumanDataAppearanceTypeMemberType
# HumanDataDatabaseType
# HumanDataDatabaseTypeMemberType
# HumanDataEditDisplayBodyParts
# HumanDataEditDisplayBodyPartsMemberType
# HumanDataGenderType
# HumanDataGenderTypeMemberType
# HumanDataHandFootType
# HumanDataHandFootTypeMemberType
# HumanDataHandGoalType
# HumanDataHandGoalTypeMemberType
# HumanDataInverseKinematicsBalanceType
# HumanDataInverseKinematicsBalanceTypeMemberType
# HumanDataInverseKinematicsBodyParts
# HumanDataInverseKinematicsBodyPartsMemberType
# HumanDataInverseKinematicsHeadEyeType
# HumanDataInverseKinematicsHeadEyeTypeMemberType
# HumanDataInverseKinematicsInitJoint
# HumanDataInverseKinematicsInitJointMemberType
# HumanDataInverseKinematicsType
# HumanDataInverseKinematicsTypeMemberType
# HumanDataJointType
# HumanDataJointTypeMemberType
# HumanDataReferencePointType
# HumanDataReferencePointTypeMemberType
# HumanDataSegmentScalingType
# HumanDataSegmentScalingTypeMemberType
# HumanDataSideType
# HumanDataSideTypeMemberType
# HumanDataStatureType
# HumanDataStatureTypeMemberType
# HumanDataStatureUnitType
# HumanDataStatureUnitTypeMemberType
# HumanDataWeightType
# HumanDataWeightTypeMemberType
# HumanDataWeightUnitType
# HumanDataWeightUnitTypeMemberType
# HumanHandShapeData
# HumanHandShapeDataHandOpt
# HumanHandShapeDataHandOptMemberType
# HumanHandsDialogBuilder
# HumanHandsDialogBuilderBreadthType
# HumanHandsDialogBuilderBreadthTypeMemberType
# HumanHandsDialogBuilderDatabaseType
# HumanHandsDialogBuilderDatabaseTypeMemberType
# HumanHandsDialogBuilderGenderType
# HumanHandsDialogBuilderGenderTypeMemberType
# HumanHandsDialogBuilderHandType
# HumanHandsDialogBuilderHandTypeMemberType
# HumanHandsDialogBuilderLengthType
# HumanHandsDialogBuilderLengthTypeMemberType
# HumanHandsDialogBuilderStyleType
# HumanHandsDialogBuilderStyleTypeMemberType
# HumanPosturePrediction
# HumanPosturePredictionBuilder
# HumanPosturePredictionBuilderCushionFirmnessType
# HumanPosturePredictionBuilderCushionFirmnessTypeMemberType
# HumanPosturePredictionBuilderGarbType
# HumanPosturePredictionBuilderGarbTypeMemberType
# HumanPosturePredictionBuilderOccupantType
# HumanPosturePredictionBuilderOccupantTypeMemberType
# HumanPosturePredictionBuilderPredictionMethodType
# HumanPosturePredictionBuilderPredictionMethodTypeMemberType
# HumanPosturePredictionBuilderSeatType
# HumanPosturePredictionBuilderSeatTypeMemberType
# HumanPosturePredictionBuilderSteeringWheelPedalType
# HumanPosturePredictionBuilderSteeringWheelPedalTypeMemberType
# HumanPosturePredictionBuilderTransmissionType
# HumanPosturePredictionBuilderTransmissionTypeMemberType
# HumanPosturePredictionBuilderVehicleType
# HumanPosturePredictionBuilderVehicleTypeMemberType
# HumanReachZone
# HumanReachZoneMethodType
# HumanReachZoneMethodTypeMemberType
# Hyperbola
# HyperbolaCollection
# IAttributeSourceObjectBuilder
# IBaseCurve
# IBasePlane
# IBody
# ICurve
# IExternalFileReferencer
# IFacet
# IFitTo
# ILocation
# INXObject
# IOrientation
# IParameterizedSurface
# IPlane
# IProfile
# IReferenceAxis
# ISketchHelpedConstraint
# ISurface
# ITableEditorDataProvider
# IfcCreator
# IfcCreatorIfcFormatEnum
# IfcCreatorIfcFormatEnumMemberType
# IfcCreatorUnitsEnum
# IfcCreatorUnitsEnumMemberType
# IfcImporter
# IfcImporterImportFacetsAsXTBrepOrConvergentEnum
# IfcImporterImportFacetsAsXTBrepOrConvergentEnumMemberType
# IfcImporterMessageEnum
# IfcImporterMessageEnumMemberType
# IfcImporterMoveDataEnum
# IfcImporterMoveDataEnumMemberType
# IgesCreator
# IgesCreatorCrossHatchMapEnum
# IgesCreatorCrossHatchMapEnumMemberType
# IgesCreatorCsysrefEnum
# IgesCreatorCsysrefEnumMemberType
# IgesCreatorExportFromOption
# IgesCreatorExportFromOptionMemberType
# IgesCreatorMapRevolvedFacesOption
# IgesCreatorMapRevolvedFacesOptionMemberType
# IgesImporter
# IgesImporterCopiousDataEnum
# IgesImporterCopiousDataEnumMemberType
# IgesImporterImportToEnum
# IgesImporterImportToEnumMemberType
# ImportManager
# Importer
# Importer3MF
# Importer3MFFacetBodyTypes
# Importer3MFFacetBodyTypesMemberType
# InferSnapType
# InferSnapTypeSnapType
# InferSnapTypeSnapTypeMemberType
# InferredConstraintsBuilder
# InfiniteLine
# InfiniteLineCollection
# Information
# InformationDisplayFeatureType
# InformationDisplayFeatureTypeMemberType
# InterpartExpressionsBuilder
# InterpartExpressionsBuilderNamingRules
# InterpartExpressionsBuilderNamingRulesMemberType
# ItemCacheMappedEntityBuilder
# JamNXColorRgb_Struct
# JamSessionAllocationStatistics_Struct
# JamTestStruct1_Struct
# JamTestStruct2_Struct
# JamTestStruct3_Struct
# JamTestStruct4_Struct
# JamTestStruct5_Struct
# JamTestStructPropertyStruct_Struct
# JamTestStructWithTypesFromNestedNamespaceOmpp_Struct
# JamTestStructWithTypesFromNestedNamespace_Struct
# JournalManager
# JtCreator
# JtCreatorAdvancedMaterials
# JtCreatorAdvancedMaterialsMemberType
# JtCreatorChordalValue
# JtCreatorChordalValueMemberType
# JtCreatorFileStructure
# JtCreatorFileStructureMemberType
# JtCreatorFileWrite
# JtCreatorFileWriteMemberType
# JtCreatorPmiOption
# JtCreatorPmiOptionMemberType
# JtCreatorRefsetOption
# JtCreatorRefsetOptionMemberType
# JtCreatorTessellationOption
# JtCreatorTessellationOptionMemberType
# KFObject
# KdaTemplateTestManager
# KdaUITemplateTestManager
# Layout
# LayoutCollection
# LayoutDefinition
# LayoutDefinitionArrangementType
# LayoutDefinitionArrangementTypeMemberType
# LicenseManager
# LicenseManagerLicenseBundle_Struct
# Light
# LightCollection
# LightSceneType
# LightSceneTypeMemberType
# LightType
# LightTypeMemberType
# Line
# LineCollection
# LineColorFontWidthBuilder
# LineDesignerTemplateTestManager
# LineDesignerUITemplateTestManager
# LineFontBuilder
# LineFontBuilderLineFontOption
# LineFontBuilderLineFontOptionMemberType
# LineFontBuilderLineFontType
# LineFontBuilderLineFontTypeMemberType
# LineFontOption
# LineFontOptionMemberType
# LineWidthBuilder
# LineWidthOption
# LineWidthOptionMemberType
# LinkedMirrorPartAttributeEditData
# LinkedMirrorPartAttributeEditEvent
# LinkedMirrorPartBuilder
# LinkedMirrorPartBuilderMirrorCsysOption
# LinkedMirrorPartBuilderMirrorCsysOptionMemberType
# LinkedMirrorPartBuilderMirrorPartTypeOption
# LinkedMirrorPartBuilderMirrorPartTypeOptionMemberType
# LinkedMirrorPartEntityMapData
# LinkedMirrorPartEntityMapEvent
# LinkedPartManager
# ListCreator
# ListCreatorList
# ListCreatorResolutionType
# ListCreatorResolutionTypeMemberType
# ListCreatorTessellationOption
# ListCreatorTessellationOptionMemberType
# ListingWindow
# ListingWindowDeviceType
# ListingWindowDeviceTypeMemberType
# LoadOptions
# LoadOptionsBookmarkComponents
# LoadOptionsBookmarkComponentsMemberType
# LoadOptionsBookmarkRefsets
# LoadOptionsBookmarkRefsetsMemberType
# LoadOptionsLoadComponents
# LoadOptionsLoadComponentsMemberType
# LoadOptionsLoadMethod
# LoadOptionsLoadMethodMemberType
# LoadOptionsLoadOption
# LoadOptionsLoadOptionMemberType
# LoadOptionsManagedModeLoadMethod
# LoadOptionsManagedModeLoadMethodMemberType
# LoadOptionsParent
# LoadOptionsParentMemberType
# LoadOptionsUpdateSubsetOnLoad
# LoadOptionsUpdateSubsetOnLoadMemberType
# LogFile
# MWUpdate
# MassPropertiesBuilder
# MassPropertiesBuilderUpdateOptions
# MassPropertiesBuilderUpdateOptionsMemberType
# Material
# MaterialManager
# MaterialUtilities
# MaterialUtilitiesStressStrainData
# MaterialUtilitiesStressStrainDataMemberType
# MathUtils
# Matrix3x3
# Matrix4x4
# Measure
# MeasureAngle
# MeasureAngleBuilder
# MeasureAngleBuilderAngleType
# MeasureAngleBuilderAngleTypeMemberType
# MeasureAngleBuilderObjectType
# MeasureAngleBuilderObjectTypeMemberType
# MeasureAngleBuilderOrientationType
# MeasureAngleBuilderOrientationTypeMemberType
# MeasureAngleBuilderProjectionType
# MeasureAngleBuilderProjectionTypeMemberType
# MeasureBodies
# MeasureBodiesActiveValue
# MeasureBodiesActiveValueMemberType
# MeasureBodiesAnalysisUnit
# MeasureBodiesAnalysisUnitMemberType
# MeasureBodyBuilder
# MeasureBuilder
# MeasureBuilderAnnotationType
# MeasureBuilderAnnotationTypeMemberType
# MeasureBuilderRequirementType
# MeasureBuilderRequirementTypeMemberType
# MeasureDistance
# MeasureDistanceBuilder
# MeasureDistanceBuilderDistanceType
# MeasureDistanceBuilderDistanceTypeMemberType
# MeasureDistanceBuilderMeasureType
# MeasureDistanceBuilderMeasureTypeMemberType
# MeasureElement
# MeasureElementMeasure
# MeasureElementMeasureMemberType
# MeasureExtremePoint
# MeasureFaceBuilder
# MeasureFaces
# MeasureFacesActiveValue
# MeasureFacesActiveValueMemberType
# MeasureLength
# MeasureManager
# MeasureManagerEndpointType
# MeasureManagerEndpointTypeMemberType
# MeasureManagerExtremeType
# MeasureManagerExtremeTypeMemberType
# MeasureManagerMeasureType
# MeasureManagerMeasureTypeMemberType
# MeasureManagerProjectionType
# MeasureManagerProjectionTypeMemberType
# MeasureManagerRadialMeasureType
# MeasureManagerRadialMeasureTypeMemberType
# MeasureMaster
# MeasureMasterBuilder
# MeasureMasterSequence
# MeasureMasterSequenceMemberType
# MeasurePoint
# MeasurePolarAngle
# MeasurePolarArea
# MeasurePolarRadius
# MeasureRectangularExtreme
# Measurement
# MeasurementDeviationReportType
# MeasurementDeviationReportTypeMemberType
# MeshParameterData
# MeshParameterDataFeatureType
# MeshParameterDataFeatureTypeMemberType
# MeshParameterDataType
# MeshParameterDataTypeMemberType
# MeshProfileString
# MeshProfileStringInsertOrder
# MeshProfileStringInsertOrderMemberType
# MeshProfileStringSelectedPoint
# MeshProfileStringSelectedPointMemberType
# MeshProfileStringType
# MeshProfileStringTypeMemberType
# ModelingAutotestPrintSmartCurveDeviationData_Struct
# ModelingView
# ModelingViewCollection
# ModelingViewHighQualityImage
# ModelingViewHighQualityImageDisplayTechniqueType
# ModelingViewHighQualityImageDisplayTechniqueTypeMemberType
# ModelingViewHighQualityImageFormatType
# ModelingViewHighQualityImageFormatTypeMemberType
# ModelingViewHighQualityImageShadeMethod
# ModelingViewHighQualityImageShadeMethodMemberType
# ModelingViewList
# ModlConstraint
# ModlConstraintRelationType
# ModlConstraintRelationTypeMemberType
# ModlTemplateTestManager
# ModlUITemplateTestManager
# MorphMeshTaskEnvironment
# MovieManager
# MovieSettingsBuilder
# MovieSettingsBuilderCaptureAreaChoices
# MovieSettingsBuilderCaptureAreaChoicesMemberType
# MovieSettingsBuilderPlaybackSpeedChoices
# MovieSettingsBuilderPlaybackSpeedChoicesMemberType
# NXColor
# NXColorRgb_Struct
# NXException
# NXMatrix
# NXMatrixCollection
# NXMessageBox
# NXMessageBoxDialogType
# NXMessageBoxDialogTypeMemberType
# NXObject
# NXObjectAttributeInformation_Struct
# NXObjectAttributeType
# NXObjectAttributeTypeMemberType
# NXObjectComputationalTime_Struct
# NXObjectDateAndTimeFormat
# NXObjectDateAndTimeFormatMemberType
# NXObjectList
# NXPlatformTestSession
# NXTo2dCreator
# NXTo2dCreatorExportDataOption
# NXTo2dCreatorExportDataOptionMemberType
# NXTo2dCreatorExportFromOption
# NXTo2dCreatorExportFromOptionMemberType
# NXTo2dCreatorOutputAsOption
# NXTo2dCreatorOutputAsOptionMemberType
# NXTo2dCreatorOutputToOption
# NXTo2dCreatorOutputToOptionMemberType
# NXTranslatorsAutotestPrintDatasetInfo_Struct
# NavigatorFilter
# NxFacet
# NxsmTemplateTestManager
# NxsmUITemplateTestManager
# OMAttributeInfo_Struct
# ObjectGeneralPropertiesBuilder
# ObjectList
# ObjectListDeleteOption
# ObjectListDeleteOptionMemberType
# ObjectSelector
# ObjectSelectorScope
# ObjectSelectorScopeMemberType
# ObjectTypeSelector
# Offset
# OffsetCollection
# OffsetOnFaceOption
# OffsetOnFaceOptionMemberType
# OriginMethod
# OriginMethodMemberType
# OuterEdgesOfFacesRule
# PDMDebugSessionNxPartInfoFlags_Struct
# PDMDebugSessionPerformanceStatistics_Struct
# PDMDebugSessionTcPartInfoFlags_Struct
# PDMDebugSessionWorksetInformationFlags_Struct
# Parabola
# ParabolaCollection
# ParamLibLibraryManagerBuilder
# ParamLibParameter
# ParamLibParameterBuilder
# ParamLibParameterCollection
# ParamLibParameterLibraryManager
# ParamLibParameterListBuilder
# ParameterTable
# ParameterTableCollection
# Part
# PartCleanup
# PartCleanupCleanupParts
# PartCleanupCleanupPartsMemberType
# PartCleanupDeleteGroups
# PartCleanupDeleteGroupsMemberType
# PartCleanupResetComponentDisplayAction
# PartCleanupResetComponentDisplayActionMemberType
# PartCloseResponses
# PartCloseStatus
# PartCollection
# PartCollectionMultipleDisplayedPartStatus
# PartCollectionMultipleDisplayedPartStatusMemberType
# PartCollectionRefsetOption
# PartCollectionRefsetOptionMemberType
# PartCollectionSdpsStatus
# PartCollectionSdpsStatusMemberType
# PartCollectionSetProtectionOn
# PartCollectionSetProtectionOnMemberType
# PartCollectionWorkComponentOption
# PartCollectionWorkComponentOptionMemberType
# PartDelayedUpdateStatus
# PartDelayedUpdateStatusDelayStatusInfo_Struct
# PartDisplayPartWorkPartOption
# PartDisplayPartWorkPartOptionMemberType
# PartFamilyManager
# PartFamilyMemberData
# PartFamilyMemberValues
# PartFeatureUpdateStatus_Struct
# PartImporter
# PartImporterDestinationCoordinateSystemSpecificationType
# PartImporterDestinationCoordinateSystemSpecificationTypeMemberType
# PartImporterLayerOptionType
# PartImporterLayerOptionTypeMemberType
# PartLoadState
# PartLoadStateMemberType
# PartLoadStatus
# PartPartFamilyAttrType
# PartPartFamilyAttrTypeMemberType
# PartPartFamilyAttributeData_Struct
# PartRelations
# PartRelationsMemberType
# PartReopenReport
# PartReopenStatus
# PartSaveOptions
# PartSaveOptionsPatternData
# PartSaveOptionsPatternDataMemberType
# PartSaveStatus
# PartUnits
# PartUnitsMemberType
# PasteSpecialBuilder
# PasteSpecialBuilderDestinationOption
# PasteSpecialBuilderDestinationOptionMemberType
# PasteSpecialBuilderLayerOption
# PasteSpecialBuilderLayerOptionMemberType
# PerfTemplateTestManager
# PerfUITemplateTestManager
# PerformanceManagerOutputDevice
# PerformanceManagerOutputDeviceMemberType
# Persistence
# PersistenceMemberType
# PhysicalMaterial
# PhysicalMaterialAssignWarning
# PhysicalMaterialAssignWarningMemberType
# PhysicalMaterialBuilder
# PhysicalMaterialCategory
# PhysicalMaterialCategoryMemberType
# PhysicalMaterialCollection
# PhysicalMaterialType
# PhysicalMaterialTypeMemberType
# PidDebugSession
# Plane
# PlaneCollection
# PlaneList
# PlaneNormalOrientation
# PlaneNormalOrientationMemberType
# PlaneTypes
# PlaneTypesAlternateType
# PlaneTypesAlternateTypeMemberType
# PlaneTypesFrenetSubtype
# PlaneTypesFrenetSubtypeMemberType
# PlaneTypesMethodType
# PlaneTypesMethodTypeMemberType
# PlotBuilder
# PlotBuilderImageResolutionOption
# PlotBuilderImageResolutionOptionMemberType
# PlotBuilderJustificationOption
# PlotBuilderJustificationOptionMemberType
# PlotBuilderPlotTypes
# PlotBuilderPlotTypesMemberType
# PlotBuilderRotationOption
# PlotBuilderRotationOptionMemberType
# PlotBuilderUnitsOption
# PlotBuilderUnitsOptionMemberType
# PlotBuilderXdisplayOption
# PlotBuilderXdisplayOptionMemberType
# PlotBuilderYdisplayOption
# PlotBuilderYdisplayOptionMemberType
# PlotColorsWidthsBuilder
# PlotColorsWidthsBuilderColor
# PlotColorsWidthsBuilderColorMemberType
# PlotColorsWidthsBuilderWidth
# PlotColorsWidthsBuilderWidthMemberType
# PlotManager
# PlotSourceBuilder
# Point
# Point2d
# Point3d
# Point4d
# PointCollection
# PointCollectionAlongCurveOption
# PointCollectionAlongCurveOptionMemberType
# PointCollectionPointOnCurveLocationOption
# PointCollectionPointOnCurveLocationOptionMemberType
# PointList
# PolygonModelingTaskEnvironment
# Polyline
# PolylineCollection
# PositioningDimension
# PositioningDimensionSubtype
# PositioningDimensionSubtypeMemberType
# PreviewBuilder
# PreviewPropertiesBuilder
# PreviewPropertiesBuilderModelViewCreationOptions
# PreviewPropertiesBuilderModelViewCreationOptionsMemberType
# PreviewPropertiesBuilderPartCreationOptions
# PreviewPropertiesBuilderPartCreationOptionsMemberType
# PrimitiveFacetsRule
# Print3dBuilder
# Print3dBuilderPrintInfillEnum
# Print3dBuilderPrintInfillEnumMemberType
# Print3dBuilderPrintQualityEnum
# Print3dBuilderPrintQualityEnumMemberType
# PrintBuilder
# PrintBuilderImageResolutionOption
# PrintBuilderImageResolutionOptionMemberType
# PrintBuilderOrientationOption
# PrintBuilderOrientationOptionMemberType
# PrintBuilderOutputOption
# PrintBuilderOutputOptionMemberType
# PrintBuilderPaperSize
# PrintBuilderPaperSizeMemberType
# PrintPDFBuilder
# PrintPDFBuilderActionOption
# PrintPDFBuilderActionOptionMemberType
# PrintPDFBuilderColor
# PrintPDFBuilderColorMemberType
# PrintPDFBuilderImageResolutionOption
# PrintPDFBuilderImageResolutionOptionMemberType
# PrintPDFBuilderOutputTextOption
# PrintPDFBuilderOutputTextOptionMemberType
# PrintPDFBuilderRelationOption
# PrintPDFBuilderRelationOptionMemberType
# PrintPDFBuilderSizeOption
# PrintPDFBuilderSizeOptionMemberType
# PrintPDFBuilderUnitsOption
# PrintPDFBuilderUnitsOptionMemberType
# PrintPDFBuilderWidth
# PrintPDFBuilderWidthMemberType
# ProeImporter
# ProeImporterImportToOption
# ProeImporterImportToOptionMemberType
# PropertiesManager
# PropertyContainer
# PropertyContainerListMode
# PropertyContainerListModeMemberType
# PropertyContainerPropertyType
# PropertyContainerPropertyTypeMemberType
# PsaTemplateTestManager
# PsaUITemplateTestManager
# PsasmTemplateTestManager
# PsasmUITemplateTestManager
# PvtransManager
# ReferenceSet
# RegionBoundaryRule
# RegionPoint
# RegionPointList
# RelationFinderSettingsBuilder
# RemoteUtilities
# ReplaceExpressionsBuilder
# RibTopFaceEdgesRule
# RotationDirection
# RotationDirectionMemberType
# RoughBrushFacetsRule
# RoutTemplateTestManager
# RoutUITemplateTestManager
# RoutingAutotestPrintObjectsToValidate_Struct
# RoutingAutotestPrintValidateOptions_Struct
# RuleManager
# RuleManagerAdoptableTypes_Struct
# RuleManagerDebugInstance_Struct
# RuleManagerDebugRule_Struct
# RuleManagerFilter
# RuleManagerFilterMemberType
# RuleManagerFunctionArgumentsInformation_Struct
# RuleManagerFunctionInformation_Struct
# RuleManagerInitializationStatusType
# RuleManagerInitializationStatusTypeMemberType
# RuleManagerLicenseType
# RuleManagerLicenseTypeMemberType
# RuleManagerParameterRule_Struct
# RuleManagerRuleType
# RuleManagerRuleTypeMemberType
# STLCreator
# STLCreatorOutputTypeEnum
# STLCreatorOutputTypeEnumMemberType
# STLCreatorSheetBodyExportOptionEnum
# STLCreatorSheetBodyExportOptionEnumMemberType
# STLImporter
# STLImporterAngularToleranceType
# STLImporterAngularToleranceTypeMemberType
# STLImporterFileFormatType
# STLImporterFileFormatTypeMemberType
# STLImporterFileUnitsType
# STLImporterFileUnitsTypeMemberType
# SaveOptions
# ScCollector
# ScCollectorAllowTypes
# ScCollectorAllowTypesMemberType
# ScCollectorCollection
# ScCollectorList
# ScEvaluationFiltertype
# ScEvaluationFiltertypeMemberType
# ScRuleFactory
# Scalar
# ScalarCollection
# ScalarDimensionalityType
# ScalarDimensionalityTypeMemberType
# ScalarMatrixValue
# ScalarTableValue
# SdpdAutotest
# Section
# SectionAllowTypes
# SectionAllowTypesMemberType
# SectionCollection
# SectionCollectionLoopOption
# SectionCollectionLoopOptionMemberType
# SectionData
# SectionDeselectOption
# SectionDeselectOptionMemberType
# SectionElementData
# SectionList
# SectionMode
# SectionModeMemberType
# SelectBody
# SelectBodyList
# SelectCartesianCoordinateSystem
# SelectCoordinateSystem
# SelectCoordinateSystemList
# SelectCurve
# SelectCurveList
# SelectDatumPlane
# SelectDatumPlaneList
# SelectDisplayableObject
# SelectDisplayableObjectList
# SelectEdge
# SelectEdgeList
# SelectExpressionList
# SelectFace
# SelectFaceList
# SelectGroup
# SelectIBaseCurve
# SelectIBaseCurveList
# SelectIBasePlaneList
# SelectIBody
# SelectICurve
# SelectICurveList
# SelectINXObjectList
# SelectIParameterizedSurface
# SelectIParameterizedSurfaceList
# SelectIReferenceAxis
# SelectISurface
# SelectLine
# SelectModelingViewList
# SelectNXObject
# SelectNXObjectList
# SelectObject
# SelectObjectList
# SelectPart
# SelectPartList
# SelectPoint
# SelectPointList
# SelectSketch
# SelectSketchFixObjectsBuilderList
# SelectSketchList
# SelectSketchMakeUniformScaleBuilderList
# SelectSmartObject
# SelectSpline
# SelectSplineList
# SelectTaggedObject
# SelectTaggedObjectList
# SelectView
# SelectViewList
# Selection
# SelectionDialogResponse
# SelectionDialogResponseMemberType
# SelectionHandle
# SelectionIntentRule
# SelectionIntentRuleRuleType
# SelectionIntentRuleRuleTypeMemberType
# SelectionMaskTriple_Struct
# SelectionMethod
# SelectionResponse
# SelectionResponseMemberType
# SelectionSelectionAction
# SelectionSelectionActionMemberType
# SelectionSelectionDescriptor_Struct
# SelectionSelectionFeatureType
# SelectionSelectionFeatureTypeMemberType
# SelectionSelectionScope
# SelectionSelectionScopeMemberType
# SelectionSelectionType
# SelectionSelectionTypeMemberType
# SelectionSubscriber
# SelectionUistylerSelectionType
# SelectionUistylerSelectionTypeMemberType
# Sense
# SenseMemberType
# Session
# SessionLibraryUnloadOption
# SessionLibraryUnloadOptionMemberType
# SessionMarkVisibility
# SessionMarkVisibilityMemberType
# SessionProjectAssignmentObjectType
# SessionProjectAssignmentObjectTypeMemberType
# SessionProjectAssignmentState
# SessionProjectAssignmentStateMemberType
# SessionTransientPartPolicy
# SessionTransientPartPolicyMemberType
# SessionUndoMarkData_Struct
# SingleFacetRule
# SingleMeasure
# Sketch
# SketchAddEllipseOption
# SketchAddEllipseOptionMemberType
# SketchAlignmentConstraint
# SketchAlignmentConstraintType
# SketchAlignmentConstraintTypeMemberType
# SketchAlongPathBuilder
# SketchAlongPathBuilderPlaneOrientationType
# SketchAlongPathBuilderPlaneOrientationTypeMemberType
# SketchAlongPathBuilderSketchOrientationType
# SketchAlongPathBuilderSketchOrientationTypeMemberType
# SketchAlternateSolutionOption
# SketchAlternateSolutionOptionMemberType
# SketchAngularDimensionBuilder
# SketchAssocType
# SketchAssocTypeMemberType
# SketchAssociativeTrim
# SketchAssociativeTrimBuilder
# SketchAssociativeTrimBuilderTrimOption
# SketchAssociativeTrimBuilderTrimOptionMemberType
# SketchAutoConstrainBuilder
# SketchAutoDimensionBuilder
# SketchAutoDimensionBuilderDimType
# SketchAutoDimensionBuilderDimTypeMemberType
# SketchAutoDimensioningRule
# SketchAutoDimensioningRuleMemberType
# SketchChamferBuilder
# SketchChamferBuilderChamferOptions
# SketchChamferBuilderChamferOptionsMemberType
# SketchCollection
# SketchConicBuilder
# SketchConstraint
# SketchConstraintBuilder
# SketchConstraintBuilderConstraint
# SketchConstraintBuilderConstraintMemberType
# SketchConstraintClass
# SketchConstraintClassMemberType
# SketchConstraintGeometryHelpType
# SketchConstraintGeometryHelpTypeMemberType
# SketchConstraintGeometryHelp_Struct
# SketchConstraintGeometry_Struct
# SketchConstraintPointType
# SketchConstraintPointTypeMemberType
# SketchConstraintType
# SketchConstraintTypeMemberType
# SketchCopyObjectData_Struct
# SketchCornerBuilder
# SketchCreateDimensionOption
# SketchCreateDimensionOptionMemberType
# SketchCreateInferConstraintSetting
# SketchCreateInferConstraintSettingMemberType
# SketchDefineWorkRegionBuilder
# SketchDefineWorkRegionBuilderScopeType
# SketchDefineWorkRegionBuilderScopeTypeMemberType
# SketchDeleteThirdCurveOption
# SketchDeleteThirdCurveOptionMemberType
# SketchDimensionBuilder
# SketchDimensionBuilderExpOption
# SketchDimensionBuilderExpOptionMemberType
# SketchDimensionGeometry_Struct
# SketchDimensionOption
# SketchDimensionOptionMemberType
# SketchDimensionalConstraint
# SketchDimensionalConstraintDimensionStateType
# SketchDimensionalConstraintDimensionStateTypeMemberType
# SketchDimensionalConstraintEndBehaviorPreference
# SketchDimensionalConstraintEndBehaviorPreferenceMemberType
# SketchEditDefiningSectionBuilder
# SketchEditDimensionValueBuilder
# SketchEllipseBuilder
# SketchEvaluator
# SketchEvaluatorCollection
# SketchExpressionModifierBuilder
# SketchExpressionModifierBuilderEndCuts
# SketchExpressionModifierBuilderEndCutsMemberType
# SketchFindMovableObjectsBuilder
# SketchFixObjectsBuilder
# SketchG1Constraint
# SketchG1ConstraintSlopeType
# SketchG1ConstraintSlopeTypeMemberType
# SketchG2Constraint
# SketchGeometricConstraint
# SketchHelpedDimensionalConstraint
# SketchHelpedGeometricConstraint
# SketchIgnoreRelationBuilder
# SketchInDraftingBuilder
# SketchInPlaceBuilder
# SketchIncludeGeometryBuilder
# SketchInferConstraintsOption
# SketchInferConstraintsOptionMemberType
# SketchIntersectionCurve
# SketchIntersectionCurveBuilder
# SketchIntersectionPoint
# SketchIntersectionPointBuilder
# SketchLinearDimensionBuilder
# SketchMakeCoincidentBuilder
# SketchMakeCollinearBuilder
# SketchMakeEqualBuilder
# SketchMakeEqualBuilderEqualTypes
# SketchMakeEqualBuilderEqualTypesMemberType
# SketchMakeHorizontalBuilder
# SketchMakeMidpointAlignedBuilder
# SketchMakeParallelBuilder
# SketchMakePerpendicularBuilder
# SketchMakePerpendicularToStringBuilder
# SketchMakePointOnStringBuilder
# SketchMakeRelationBuilder
# SketchMakeRelationBuilderRelationTypes
# SketchMakeRelationBuilderRelationTypesMemberType
# SketchMakeSymmetricBuilder
# SketchMakeTangentBuilder
# SketchMakeTangentToStringBuilder
# SketchMakeUniformScaleBuilder
# SketchMakeVerticalBuilder
# SketchManageSymmetryLinesBuilder
# SketchMirrorPatternBuilder
# SketchOffset
# SketchOffsetBuilder
# SketchOffsetCapType
# SketchOffsetCapTypeMemberType
# SketchOperationBuilder
# SketchPasteBuilder
# SketchPattern
# SketchPatternBuilder
# SketchPatternInstanceControl
# SketchPatternInstanceControlMemberType
# SketchPatternType
# SketchPatternTypeMemberType
# SketchPlaneOption
# SketchPlaneOptionMemberType
# SketchPolygon
# SketchPolygonBuilder
# SketchPolygonBuilderSizeType
# SketchPolygonBuilderSizeTypeMemberType
# SketchProjectBuilder
# SketchProjectBuilderOutputCurve
# SketchProjectBuilderOutputCurveMemberType
# SketchQuickExtendBuilder
# SketchQuickTrimBuilder
# SketchRadialDimensionBuilder
# SketchRapidDimensionBuilder
# SketchRelation
# SketchRelationFinder
# SketchStatus
# SketchStatusMemberType
# SketchSymmetricBuilder
# SketchTangentConstraint
# SketchTangentToStringConstraint
# SketchTrimInputOption
# SketchTrimInputOptionMemberType
# SketchUpdateLevel
# SketchUpdateLevelMemberType
# SketchViewReorient
# SketchViewReorientMemberType
# SketchVirtualPoint
# SmartObject
# SmartObjectUpdateOption
# SmartObjectUpdateOptionMemberType
# SmartObjectVisibilityOption
# SmartObjectVisibilityOptionMemberType
# SphericalCoordinateSystem
# Spline
# SplineCollection
# Spreadsheet
# SpreadsheetCellData
# SpreadsheetCellDataTypes
# SpreadsheetCellDataTypesMemberType
# SpreadsheetExternal
# SpreadsheetManager
# SpreadsheetManagerLookupMode
# SpreadsheetManagerLookupModeMemberType
# SpreadsheetManagerOpenMode
# SpreadsheetManagerOpenModeMemberType
# SpreadsheetManagerSheettype
# SpreadsheetManagerSheettypeMemberType
# Step203Importer
# Step203ImporterImportToOption
# Step203ImporterImportToOptionMemberType
# Step214Importer
# Step214ImporterImportToOption
# Step214ImporterImportToOptionMemberType
# Step242Importer
# Step242ImporterImportToOption
# Step242ImporterImportToOptionMemberType
# Step242ImporterMessageEnum
# Step242ImporterMessageEnumMemberType
# StepCreator
# StepCreatorEntityNameOption
# StepCreatorEntityNameOptionMemberType
# StepCreatorExportAsOption
# StepCreatorExportAsOptionMemberType
# StepCreatorExportFromOption
# StepCreatorExportFromOptionMemberType
# StepCreatorExportSolidsAndSurfacesAsOption
# StepCreatorExportSolidsAndSurfacesAsOptionMemberType
# StepCreatorExternalReferenceStructureOption
# StepCreatorExternalReferenceStructureOptionMemberType
# StudioMaterialManager
# SubdivisionMeshBody
# SubdivisionMeshEdge
# SubdivisionMeshFace
# SubdivisionMeshVertex
# SubdivisionTaskEnvironment
# SuppressByExpressionBuilder
# SuppressByExpressionBuilderExpressionAction
# SuppressByExpressionBuilderExpressionActionMemberType
# SurfaceRebuildData
# SurfaceRebuildDataType
# SurfaceRebuildDataTypeMemberType
# SurfaceUVDirectionBuilder
# SymbolFont
# TCINDebugSessionAttributeInput_Struct
# TCINDebugSessionTestUtilsAttributeInput_Struct
# TCINDebugSessionTestUtilsCustomDECreationInputFlags_Struct
# TCINDebugSessionTestUtilsCustomDECreationInput_Struct
# TCINDebugSessionTestUtilsCustomItemCreationInputFlags_Struct
# TCINDebugSessionTestUtilsCustomItemCreationInput_Struct
# TCINDebugSessionTestUtilsCustomShapeItemCreationInputFlags_Struct
# TCINDebugSessionTestUtilsCustomShapeItemCreationInput_Struct
# TCINDebugSessionTestUtilsCustomWorksetCreationInputFlags_Struct
# TCINDebugSessionTestUtilsCustomWorksetCreationInput_Struct
# TCINDebugSessionTestUtilsProjectInputS_Struct
# TCINDebugSessionTestUtilsPromissoryDECreationInput_Struct
# TCINDebugSessionTestUtilsReuseDECreationInput_Struct
# TCINDebugSessionTestUtilsShapeDECreationInput_Struct
# TCINDebugSessionTestUtilsSubsetCreationInput_Struct
# TableEditorDefaultDataProvider
# TaggedObject
# TaggedObjectList
# TaggedObjectManager
# TangentFacetsRule
# TcinTemplateTestManager
# TcinUITemplateTestManager
# TextAlignmentModeT
# TextAlignmentModeTMemberType
# TextColorFontWidthBuilder
# TextureModelingTaskEnvironment
# ToolDesignerTemplateTestManager
# ToolDesignerUITemplateTestManager
# Traceline
# TracelineCollection
# TransientObject
# TreeListNode
# UI
# UIStatus
# UIStatusMemberType
# UITemplateTestManager
# UnderlineStyleT
# UnderlineStyleTMemberType
# Unit
# UnitCollection
# UnitCollectionUnitDefaults
# UnitCollectionUnitDefaultsMemberType
# Update
# UpdateFailureOption
# UpdateFailureOptionMemberType
# UpdateOption
# UpdateOptionMemberType
# VRMLImporter
# VRMLImporterAngularToleranceType
# VRMLImporterAngularToleranceTypeMemberType
# VRMLImporterFileUnitsType
# VRMLImporterFileUnitsTypeMemberType
# Validation
# ValidationCollection
# ValidationInputType
# ValidationInputTypeMemberType
# ValidationMapType
# ValidationMapTypeMemberType
# ValidationResult
# ValidationResultMemberType
# ValidationUpdateTime
# ValidationUpdateTimeMemberType
# Validator
# ValidatorPrintLevel
# ValidatorPrintLevelMemberType
# ValidatorType
# ValidatorTypeMemberType
# ValidatorVersion
# ValidatorVersionMemberType
# Vector3d
# View
# ViewCanned
# ViewCannedMemberType
# ViewCollection
# ViewDependentDisplayManager
# ViewDependentDisplayManagerFont
# ViewDependentDisplayManagerFontMemberType
# ViewDependentDisplayManagerPartialShading
# ViewDependentDisplayManagerPartialShadingMemberType
# ViewDependentDisplayManagerTranslucency
# ViewDependentDisplayManagerTranslucencyMemberType
# ViewDependentDisplayManagerWidth
# ViewDependentDisplayManagerWidthMemberType
# ViewRenderingStyleType
# ViewRenderingStyleTypeMemberType
# ViewScaleAdjustment
# ViewScaleAdjustmentMemberType
# ViewScaleFactor
# ViewScaleFactorMemberType
# ViewShowOrHideType
# ViewShowOrHideTypeMemberType
# ViewUIManager
# VirtuallabImporter
# VisualizationDebugSessionViewStatistics_Struct
# WCS
# WCSAxis
# WCSAxisMemberType
# WavefrontObjCreator
# WavefrontObjCreatorExportAsOption
# WavefrontObjCreatorExportAsOptionMemberType
# WavefrontObjCreatorExportFromOption
# WavefrontObjCreatorExportFromOptionMemberType
# WavefrontObjCreatorUnitsEnum
# WavefrontObjCreatorUnitsEnumMemberType
# WavefrontObjImporter
# WavefrontObjImporterGroupsEnum
# WavefrontObjImporterGroupsEnumMemberType
# WavefrontObjImporterImportAsOption
# WavefrontObjImporterImportAsOptionMemberType
# WavefrontObjImporterImportToOption
# WavefrontObjImporterImportToOptionMemberType
# WavefrontObjImporterMessageEnum
# WavefrontObjImporterMessageEnumMemberType
# WavefrontObjImporterUnitsEnum
# WavefrontObjImporterUnitsEnumMemberType
# WidthDefinition
# WithinCurvesRule
# XYZAxis
# XYZAxisMemberType
# Xform
# XformCollection
# XformCollectionAxisAndPlaneType
# XformCollectionAxisAndPlaneTypeMemberType
# XformCollectionRotationSequence
# XformCollectionRotationSequenceMemberType

class TaggedObject:
    @staticmethod
    @property
    def Null()->TaggedObject:
        pass

    @property
    def Tag(self)->int:
        pass

class NXObject(TaggedObject):
    # AttributeInformation
    # AttributeType
    # ComputationalTime
    # CreateAttributeIterator
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteUserAttribute
    # DeleteUserAttributes
    # FindObject
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # IsOccurrence
    # JournalIdentifier
    # Name
    # Null
    # OwningComponent
    # OwningPart
    # Print
    # Prototype
    # SetAttribute
    # SetBooleanUserAttribute
    # SetName
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # Tag
    pass

class DisplayableObject(NXObject):
    # AttributeInformation
    # AttributeType
    # Blank
    # Color
    # ComputationalTime
    # CreateAttributeIterator
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteUserAttribute
    # DeleteUserAttributes
    # FindObject
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # Highlight
    # IsBlanked
    # IsOccurrence
    # JournalIdentifier
    # Layer
    # LineFont
    # LineWidth
    # Name
    # NameLocation
    # Null
    # ObjectFont
    # ObjectWidth
    # OwningComponent
    # OwningPart
    # Print
    # Prototype
    # RedisplayObject
    # RemoveViewDependency
    # SetAttribute
    # SetBooleanUserAttribute
    # SetName
    # SetNameLocation
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # Tag
    # Unblank
    # Unhighlight
    pass


class Session(TaggedObject):




    @staticmethod
    def GetSession()->Session:
        pass

    @property
    def Parts(self)->PartsCollection:
        pass



class PartsCollection:
    @property
    def Display(self):
        pass

class Part:
    # AnalysisManager
    # AnalysisResults
    # AnimationCameras
    # Annotations
    # Arcs
    # Assemblies
    # AssemblyManager
    # AssignPermanentName
    # AttributeInformation
    # AttributeType
    # Axes
    # BaseFeatures
    # BlendStopshortBuilder
    # Bodies
    # BookmarkOption
    # CAMDataManager
    # CAMDataPrepManager
    # CAMFeatures
    # CAMSetup
    # CaeViewLayoutManager
    # Cameras
    # CanBeDisplayPart
    # ClipboardOperationsManager
    # Close
    # CloseAfterSave
    # CloseModified
    # CloseWholeTree
    # CollaborativeContentType
    # Colors
    # CompleteStructure
    # Component2dCollection
    # ComponentAssembly
    # ComponentDefinitions
    # ComponentGroups
    # ComputationalTime
    # ConvertPreNX9CompoundWelds
    # ConvertToPMIBuilderManager
    # CoordinateSystems
    # CreateAttributeIterator
    # CreateBoundingObjectBuilder
    # CreateCamSetup
    # CreateDynamicSectionBuilder
    # CreateEffectivityConditionBuilder
    # CreateEmptyBlendSetbackBuilder
    # CreateEmptyBoundaryDefinitionBuilder
    # CreateEmptyExpressionCollectorSet
    # CreateEmptyExpressionSectionSet
    # CreateEmptyRegionPoint
    # CreateEmptySelectionList
    # CreateEmptySpinePlaneBuilder
    # CreateEmptyTransitionCurveBuilder
    # CreateEmptyTwoExpressionsCollectorSet
    # CreateEmptyTwoExpressionsSectionSet
    # CreateExpressionCollectorSet
    # CreateExpressionSectionSet
    # CreateFacetSettingsBuilder
    # CreateGatewayGroupBuilder
    # CreateInspectionSetup
    # CreateKinematicConfigurator
    # CreateObjectList
    # CreatePartFamily
    # CreatePerspectiveOptionsBuilder
    # CreatePointSetAlignmentBuilder
    # CreatePointsFromFileBuilder
    # CreateReferenceSet
    # CreateRegionPoint
    # CreateSelectionList
    # CreateTwoExpressionsCollectorSet
    # CreateTwoExpressionsSectionSet
    # CreateWavelinkRepository
    # CurrentFeature
    # Curves
    # CutViews
    # DBEntityProxies
    # DateAndTimeFormat
    # Datums
    # Decals
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteCamSetup
    # DeleteDisplayFacets
    # DeleteInspectionSetup
    # DeleteReferenceSet
    # DeleteRetainedDraftingObjectsInCurrentLayout
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DesignStudy
    # DiagrammingManager
    # DieSimData
    # Dimensions
    # Directions
    # Displayed
    # DisplayedConstraints
    # DraftPointData
    # Drafting
    # DraftingDrawingSheets
    # DraftingManager
    # DraftingViews
    # DrawingCompare
    # DrawingSheets
    # DynamicSections
    # Ellipses
    # ExpressionGroups
    # Expressions
    # ExternalFileReferenceManager
    # FacePlaneSelectionBuilderData
    # FaceSetData
    # FaceSetOffsets
    # FacetCollectorCollection
    # FacetSelectionRuleFactory
    # FacetedBodies
    # FeatureUpdateStatus
    # Features
    # FieldManager
    # FindObject
    # Fonts
    # FullPath
    # Functions
    # GanttCollection
    # GanttLinkerCollection
    # Gdts
    # GeometryLocationData
    # GetAllReferenceSets
    # GetArrangements
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCollaborativeContentType
    # GetComputationalTimeUserAttribute
    # GetFamilyInstance
    # GetHistoryInformation
    # GetIncompleteStatus
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetInterpartChildren
    # GetInterpartParents
    # GetMakeUniqueName
    # GetMinimallyLoadedParts
    # GetNextUserAttribute
    # GetPartFamilyManager
    # GetPdmReferenceAttributeValue
    # GetPreviewImage
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetTransientStatus
    # GetUpdateStatusReport
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # Grids
    # HasAnyMinimallyLoadedChildren
    # HasReuseTemplate
    # HasUserAttribute
    # HasWriteAccess
    # HistoryEventInformation
    # Hyperbolas
    # ImageCaptureManager
    # Images
    # ImagesData
    # ImportManager
    # IncompleteStatus
    # InfiniteLines
    # InspectionSetup
    # IsBookletPart
    # IsDesignReviewPart
    # IsFullyLoaded
    # IsModified
    # IsOccurrence
    # IsReadOnly
    # JournalIdentifier
    # KinematicConfigurator
    # Labels
    # LayerCategories
    # Layers
    # LayoutDrawingSheets
    # Layouts
    # Leaf
    # Lights
    # Lines
    # LoadFeatureDataForSelection
    # LoadFully
    # LoadThisPartFully
    # LoadThisPartPartially
    # LocalDefinitionFolders
    # LocalUntrimManager
    # MakeAllFeaturesInactive
    # MakeNoPartModuleActive
    # Markers
    # Markups
    # MaterialManager
    # MeasureManager
    # MechatronicsManager
    # ModelingViews
    # MotionManager
    # NXMatrices
    # Name
    # NewPartFamilyMemberData
    # NewPartFamilyMemberValues
    # NewPartFamilyTemplateManager
    # Notes
    # Null
    # Offsets
    # OmnicadManager
    # OnestepUnforms
    # Optimization
    # OwningComponent
    # OwningPart
    # PDMPart
    # PackagingCollection
    # Parabolas
    # ParameterLibraryManager
    # ParameterTables
    # PartFamilyAttrType
    # PartFamilyAttributeData
    # PartLoadState
    # PartPreview
    # PartPreviewMode
    # PartUnits
    # PenetrationManager
    # PersistentResults
    # PhysicsManager
    # Planes
    # PlasManager
    # PlotManager
    # PmiManager
    # PmiSettingsManager
    # PointClouds
    # Points
    # Polylines
    # Preferences
    # Print
    # ProductInterface
    # PropertiesManager
    # Prototype
    # ProxyObjectCollection
    # ProxyOverrideObjectCollection
    # RegenerateDisplayFacets
    # ReinstateTransience
    # Relations
    # Relinkers
    # RemoveMissingParentsFromEdgeBlend
    # RemoveTransience
    # Reopen
    # ReopenAs
    # RequirementChecks
    # Requirements
    # ResetTimestampToLatestFeature
    # ReusableParts
    # ReverseBlankAll
    # RouteManager
    # RuleManager
    # SHEDObjs
    # Save
    # SaveAs
    # SaveBookmark
    # SaveComponents
    # SaveDisplayFacets
    # SaveOptions
    # ScCollectors
    # ScRuleFactory
    # Scalars
    # Sections
    # SegmentManager
    # SelPref
    # SetAttribute
    # SetBooleanUserAttribute
    # SetMakeUniqueName
    # SetName
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # SettingsManager
    # ShipDimensions
    # SketchEvaluators
    # Sketches
    # SmartDiagrammingManager
    # SpinePointData
    # Splines
    # SubdivisionBodies
    # Tag
    # ToolingManager
    # Tracelines
    # TransientStatus
    # TrueStudioObjs
    # UVMappingCollection
    # Undisplay
    # UniqueIdentifier
    # UnitCollection
    # Units
    # UserDefinedObjectManager
    # UserDefinedTemplates
    # Validations
    # ViewAlignments
    # ViewPreferences
    # Views
    # WCS
    # Xforms
    pass