class DisplayableObject('NXObject'):
    # AttributeInformation
    # AttributeType
    # Blank
    # Color
    # ComputationalTime
    # CreateAttributeIterator
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteUserAttribute
    # DeleteUserAttributes
    # FindObject
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # Highlight
    # IsBlanked
    # IsOccurrence
    # JournalIdentifier
    # Layer
    # LineFont
    # LineWidth
    # Name
    # NameLocation
    # Null
    # ObjectFont
    # ObjectWidth
    # OwningComponent
    # OwningPart
    # Print
    # Prototype
    # RedisplayObject
    # RemoveViewDependency
    # SetAttribute
    # SetBooleanUserAttribute
    # SetName
    # SetNameLocation
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # Tag
    # Unblank
    # Unhighlight
    pass


class Session('TaggedObject'):




    @staticmethod
    def GetSession()->'Session':
        pass

    @property
    def Parts(self)->'PartsCollection':
        pass



class PartsCollection:
    @property
    def Display(self):
        pass

class Part:
    # AnalysisManager
    # AnalysisResults
    # AnimationCameras
    # Annotations
    # Arcs
    # Assemblies
    # AssemblyManager
    # AssignPermanentName
    # AttributeInformation
    # AttributeType
    # Axes
    # BaseFeatures
    # BlendStopshortBuilder
    # Bodies
    # BookmarkOption
    # CAMDataManager
    # CAMDataPrepManager
    # CAMFeatures
    # CAMSetup
    # CaeViewLayoutManager
    # Cameras
    # CanBeDisplayPart
    # ClipboardOperationsManager
    # Close
    # CloseAfterSave
    # CloseModified
    # CloseWholeTree
    # CollaborativeContentType
    # Colors
    # CompleteStructure
    # Component2dCollection
    # ComponentAssembly
    # ComponentDefinitions
    # ComponentGroups
    # ComputationalTime
    # ConvertPreNX9CompoundWelds
    # ConvertToPMIBuilderManager
    # CoordinateSystems
    # CreateAttributeIterator
    # CreateBoundingObjectBuilder
    # CreateCamSetup
    # CreateDynamicSectionBuilder
    # CreateEffectivityConditionBuilder
    # CreateEmptyBlendSetbackBuilder
    # CreateEmptyBoundaryDefinitionBuilder
    # CreateEmptyExpressionCollectorSet
    # CreateEmptyExpressionSectionSet
    # CreateEmptyRegionPoint
    # CreateEmptySelectionList
    # CreateEmptySpinePlaneBuilder
    # CreateEmptyTransitionCurveBuilder
    # CreateEmptyTwoExpressionsCollectorSet
    # CreateEmptyTwoExpressionsSectionSet
    # CreateExpressionCollectorSet
    # CreateExpressionSectionSet
    # CreateFacetSettingsBuilder
    # CreateGatewayGroupBuilder
    # CreateInspectionSetup
    # CreateKinematicConfigurator
    # CreateObjectList
    # CreatePartFamily
    # CreatePerspectiveOptionsBuilder
    # CreatePointSetAlignmentBuilder
    # CreatePointsFromFileBuilder
    # CreateReferenceSet
    # CreateRegionPoint
    # CreateSelectionList
    # CreateTwoExpressionsCollectorSet
    # CreateTwoExpressionsSectionSet
    # CreateWavelinkRepository
    # CurrentFeature
    # Curves
    # CutViews
    # DBEntityProxies
    # DateAndTimeFormat
    # Datums
    # Decals
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteCamSetup
    # DeleteDisplayFacets
    # DeleteInspectionSetup
    # DeleteReferenceSet
    # DeleteRetainedDraftingObjectsInCurrentLayout
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DesignStudy
    # DiagrammingManager
    # DieSimData
    # Dimensions
    # Directions
    # Displayed
    # DisplayedConstraints
    # DraftPointData
    # Drafting
    # DraftingDrawingSheets
    # DraftingManager
    # DraftingViews
    # DrawingCompare
    # DrawingSheets
    # DynamicSections
    # Ellipses
    # ExpressionGroups
    # Expressions
    # ExternalFileReferenceManager
    # FacePlaneSelectionBuilderData
    # FaceSetData
    # FaceSetOffsets
    # FacetCollectorCollection
    # FacetSelectionRuleFactory
    # FacetedBodies
    # FeatureUpdateStatus
    # Features
    # FieldManager
    # FindObject
    # Fonts
    # FullPath
    # Functions
    # GanttCollection
    # GanttLinkerCollection
    # Gdts
    # GeometryLocationData
    # GetAllReferenceSets
    # GetArrangements
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCollaborativeContentType
    # GetComputationalTimeUserAttribute
    # GetFamilyInstance
    # GetHistoryInformation
    # GetIncompleteStatus
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetInterpartChildren
    # GetInterpartParents
    # GetMakeUniqueName
    # GetMinimallyLoadedParts
    # GetNextUserAttribute
    # GetPartFamilyManager
    # GetPdmReferenceAttributeValue
    # GetPreviewImage
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetTransientStatus
    # GetUpdateStatusReport
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # Grids
    # HasAnyMinimallyLoadedChildren
    # HasReuseTemplate
    # HasUserAttribute
    # HasWriteAccess
    # HistoryEventInformation
    # Hyperbolas
    # ImageCaptureManager
    # Images
    # ImagesData
    # ImportManager
    # IncompleteStatus
    # InfiniteLines
    # InspectionSetup
    # IsBookletPart
    # IsDesignReviewPart
    # IsFullyLoaded
    # IsModified
    # IsOccurrence
    # IsReadOnly
    # JournalIdentifier
    # KinematicConfigurator
    # Labels
    # LayerCategories
    # Layers
    # LayoutDrawingSheets
    # Layouts
    # Leaf
    # Lights
    # Lines
    # LoadFeatureDataForSelection
    # LoadFully
    # LoadThisPartFully
    # LoadThisPartPartially
    # LocalDefinitionFolders
    # LocalUntrimManager
    # MakeAllFeaturesInactive
    # MakeNoPartModuleActive
    # Markers
    # Markups
    # MaterialManager
    # MeasureManager
    # MechatronicsManager
    # ModelingViews
    # MotionManager
    # NXMatrices
    # Name
    # NewPartFamilyMemberData
    # NewPartFamilyMemberValues
    # NewPartFamilyTemplateManager
    # Notes
    # Null
    # Offsets
    # OmnicadManager
    # OnestepUnforms
    # Optimization
    # OwningComponent
    # OwningPart
    # PDMPart
    # PackagingCollection
    # Parabolas
    # ParameterLibraryManager
    # ParameterTables
    # PartFamilyAttrType
    # PartFamilyAttributeData
    # PartLoadState
    # PartPreview
    # PartPreviewMode
    # PartUnits
    # PenetrationManager
    # PersistentResults
    # PhysicsManager
    # Planes
    # PlasManager
    # PlotManager
    # PmiManager
    # PmiSettingsManager
    # PointClouds
    # Points
    # Polylines
    # Preferences
    # Print
    # ProductInterface
    # PropertiesManager
    # Prototype
    # ProxyObjectCollection
    # ProxyOverrideObjectCollection
    # RegenerateDisplayFacets
    # ReinstateTransience
    # Relations
    # Relinkers
    # RemoveMissingParentsFromEdgeBlend
    # RemoveTransience
    # Reopen
    # ReopenAs
    # RequirementChecks
    # Requirements
    # ResetTimestampToLatestFeature
    # ReusableParts
    # ReverseBlankAll
    # RouteManager
    # RuleManager
    # SHEDObjs
    # Save
    # SaveAs
    # SaveBookmark
    # SaveComponents
    # SaveDisplayFacets
    # SaveOptions
    # ScCollectors
    # ScRuleFactory
    # Scalars
    # Sections
    # SegmentManager
    # SelPref
    # SetAttribute
    # SetBooleanUserAttribute
    # SetMakeUniqueName
    # SetName
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # SettingsManager
    # ShipDimensions
    # SketchEvaluators
    # Sketches
    # SmartDiagrammingManager
    # SpinePointData
    # Splines
    # SubdivisionBodies
    # Tag
    # ToolingManager
    # Tracelines
    # TransientStatus
    # TrueStudioObjs
    # UVMappingCollection
    # Undisplay
    # UniqueIdentifier
    # UnitCollection
    # Units
    # UserDefinedObjectManager
    # UserDefinedTemplates
    # Validations
    # ViewAlignments
    # ViewPreferences
    # Views
    # WCS
    # Xforms
    pass


class TaggedObject:
    @staticmethod
    @property
    def Null()->'TaggedObject':
        pass

    @property
    def Tag(self)->int:
        pass

class NXObject(TaggedObject):
    # AttributeInformation
    # AttributeType
    # ComputationalTime
    # CreateAttributeIterator
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteUserAttribute
    # DeleteUserAttributes
    # FindObject
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # IsOccurrence
    # JournalIdentifier
    # Name
    # Null
    # OwningComponent
    # OwningPart
    # Print
    # Prototype
    # SetAttribute
    # SetBooleanUserAttribute
    # SetName
    # SetPdmReferenceAttribute
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # Tag
    pass