
from NXOpen import DisplayableObject, NXObject


class Component(DisplayableObject):
    # AttributeInformation
    # AttributeType
    # Blank
    # CollaborativeContentType
    # Color
    # ComputationalTime
    # CreateAttributeIterator
    # CreateEmptyPartFamilyInstanceSelectionCriteria
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteCharacterstics
    # DeleteInstanceUserAttribute
    # DeleteInstanceUserAttributes
    # DeletePartFamilyInstanceSelectionCriteria
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DesignElementRevision
    # DesignSubordinateRevision
    # DirectOwner
    # DisplayComponentsExact
    # DisplayComponentsLightweight
    # DisplayName
    # EmptyPartRefsetName
    # EntirePartRefsetName
    # EstablishIsolatedPositionOverride
    # EstablishPositionOverride
    # FindComponentPatterns
    # FindObject
    # FindOccurrence
    # FixConstraint
    # GetArrangements
    # GetAsRequiredQuantity
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCharacteristics
    # GetChildren
    # GetComponentQuantityType
    # GetComponentRepresentationMode
    # GetComputationalTimeUserAttribute
    # GetConstraints
    # GetDegreesOfFreedom
    # GetDestinationCharacteristics
    # GetInstanceBooleanUserAttribute
    # GetInstanceIntegerUserAttribute
    # GetInstanceRealUserAttribute
    # GetInstanceStringUserAttribute
    # GetInstanceTimeUserAttribute
    # GetInstanceUserAttribute
    # GetInstanceUserAttributeAsString
    # GetInstanceUserAttributeLock
    # GetInstanceUserAttributes
    # GetInstanceUserAttributesAsStrings
    # GetIntegerAttribute
    # GetIntegerCharacteristic
    # GetIntegerQuantity
    # GetIntegerUserAttribute
    # GetLayerOption
    # GetNextUserAttribute
    # GetNonGeometricState
    # GetPartFamilyInstanceSelectionCriteria
    # GetPdmReferenceAttributeValue
    # GetPosition
    # GetPositionOverrideParent
    # GetPositionOverrideType
    # GetRealAttribute
    # GetRealCharacteristic
    # GetRealQuantity
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringCharacteristic
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasInstanceUserAttribute
    # HasUserAttribute
    # Highlight
    # IsBlanked
    # IsFixed
    # IsOccurrence
    # IsPositioningIsolated
    # IsSuppressed
    # JournalIdentifier
    # Layer
    # LineFont
    # LineWidth
    # ModelElementRevision
    # Name
    # NameLocation
    # Null
    # ObjectFont
    # ObjectWidth
    # OwningComponent
    # OwningPart
    # Parent
    # Print
    # Prototype
    # RecallAndListConstraints
    # RecallConstraints
    # RedisplayObject
    # ReferenceSet
    # RemovePositionOverride
    # RemoveRememberedConstraints
    # RemoveViewDependency
    # RepresentationMode
    # SetAttribute
    # SetBooleanUserAttribute
    # SetCharacteristic
    # SetCharacteristic2
    # SetCharacteristics
    # SetCharacteristics2
    # SetInstanceBooleanUserAttribute
    # SetInstanceTimeUserAttribute
    # SetInstanceUserAttribute
    # SetInstanceUserAttributeLock
    # SetLayerOption
    # SetName
    # SetNameLocation
    # SetPartFamilyInstanceSelectionCriteria
    # SetPdmReferenceAttribute
    # SetPositioningIsolated
    # SetPositioningVaried
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUsedArrangement
    # SetUserAttribute
    # SetUserAttributeLock
    # Subset
    # Suppress
    # SuppressingArrangement
    # Tag
    # Unblank
    # Unhighlight
    # Unsuppress
    # UpdateStructure
    # UsedArrangement
    @property
    def DisplayName(self)->str:
        pass


class ComponentAssembly(NXObject):
    # ActiveArrangement
    # AddComponent
    # AddComponents
    # AddMasterPartComponent
    # AddPendingComponent
    # Arrangements
    # AttributeInformation
    # AttributeType
    # ChangeByName
    # CheckinCheckoutOption
    # CheckinComponents
    # CheckinWorkset
    # CheckoutAllModifiedObjects
    # CheckoutComponents
    # CheckoutWorkset
    # ClearanceSets
    # CloseComponents
    # CloseModified
    # ComponentPatterns
    # ComputationalTime
    # ConvertRememberedMcs
    # CopyComponents
    # CreateAttributeIterator
    # CreateComponentPatternBuilder
    # CreateConstraintGroupBuilder
    # CreateIsolateViewWithComponents
    # CreateMatingConverter
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteMatingConditions
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DrawingExplosions
    # Explosions
    # FindObject
    # GetActiveOrder
    # GetAsRequiredQuantity
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCheckedoutStatusOfObjects
    # GetComponentOrders
    # GetComponentQuantityType
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerQuantity
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetNonGeometricState
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealQuantity
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetSuppressedState
    # GetSuppressionExpression
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # HideComponentsInIsolateView
    # InsertProduct
    # IsOccurrence
    # JournalIdentifier
    # MapComponentFromParent
    # MapComponentsFromSubassembly
    # MoveComponent
    # MoveToPendingComponent
    # Name
    # Null
    # OpenComponentStatus
    # OpenComponents
    # OpenOption
    # OrderTargetLocation
    # OrdersSet
    # OwningComponent
    # OwningPart
    # Positioner
    # Print
    # Prototype
    # ReleaseSuppression
    # RemoveComponent
    # ReorderChildrenOfParent
    # ReorderComponents
    # ReplaceReferenceSet
    # ReplaceReferenceSetInOwners
    # RestructureComponents
    # RootComponent
    # SetAsRequiredQuantity
    # SetAttribute
    # SetBooleanUserAttribute
    # SetDefault
    # SetEmptyRefset
    # SetEntirePartRefset
    # SetIntegerQuantity
    # SetName
    # SetNonGeometricState
    # SetPdmReferenceAttribute
    # SetRealQuantity
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # ShowComponentsInIsolateView
    # Subsets
    # SubstituteComponent
    # SubstitutionMode
    # SuppressComponents
    # SuppressedState
    # Tag
    # UnsuppressComponents
    pass