from typing import List, Optional, Sequence, Union
from NXOpen import Builder, DisplayableObject, NXObject, Part

class Component(DisplayableObject):
    def GetChildren(self) -> Sequence[Component]: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    def SetLayerOption(self, layer: int) -> None: ...
    @property
    def IsSuppressed(self) -> bool: ...
    @property
    def Parent(self) -> Component: ...
    def Suppress(self) -> None: ...
    def Unsuppress(self) -> None: ...
    @property
    def DirectOwner(self) -> ComponentAssembly: ...

class ComponentAssembly:
    @property
    def RootComponent(self) -> Component: ...

class ReplaceComponentBuilder(Builder):
    pass
