

from NXOpen import NXObject


class ComponentAssembly(NXObject):
    # ActiveArrangement
    # AddComponent
    # AddComponents
    # AddMasterPartComponent
    # AddPendingComponent
    # Arrangements
    # AttributeInformation
    # AttributeType
    # ChangeByName
    # CheckinCheckoutOption
    # CheckinComponents
    # CheckinWorkset
    # CheckoutAllModifiedObjects
    # CheckoutComponents
    # CheckoutWorkset
    # ClearanceSets
    # CloseComponents
    # CloseModified
    # ComponentPatterns
    # ComputationalTime
    # ConvertRememberedMcs
    # CopyComponents
    # CreateAttributeIterator
    # CreateComponentPatternBuilder
    # CreateConstraintGroupBuilder
    # CreateIsolateViewWithComponents
    # CreateMatingConverter
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteMatingConditions
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DrawingExplosions
    # Explosions
    # FindObject
    # GetActiveOrder
    # GetAsRequiredQuantity
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCheckedoutStatusOfObjects
    # GetComponentOrders
    # GetComponentQuantityType
    # GetComputationalTimeUserAttribute
    # GetIntegerAttribute
    # GetIntegerQuantity
    # GetIntegerUserAttribute
    # GetNextUserAttribute
    # GetNonGeometricState
    # GetPdmReferenceAttributeValue
    # GetRealAttribute
    # GetRealQuantity
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringUserAttribute
    # GetSuppressedState
    # GetSuppressionExpression
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasUserAttribute
    # HideComponentsInIsolateView
    # InsertProduct
    # IsOccurrence
    # JournalIdentifier
    # MapComponentFromParent
    # MapComponentsFromSubassembly
    # MoveComponent
    # MoveToPendingComponent
    # Name
    # Null
    # OpenComponentStatus
    # OpenComponents
    # OpenOption
    # OrderTargetLocation
    # OrdersSet
    # OwningComponent
    # OwningPart
    # Positioner
    # Print
    # Prototype
    # ReleaseSuppression
    # RemoveComponent
    # ReorderChildrenOfParent
    # ReorderComponents
    # ReplaceReferenceSet
    # ReplaceReferenceSetInOwners
    # RestructureComponents
    # RootComponent
    # SetAsRequiredQuantity
    # SetAttribute
    # SetBooleanUserAttribute
    # SetDefault
    # SetEmptyRefset
    # SetEntirePartRefset
    # SetIntegerQuantity
    # SetName
    # SetNonGeometricState
    # SetPdmReferenceAttribute
    # SetRealQuantity
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUserAttribute
    # SetUserAttributeLock
    # ShowComponentsInIsolateView
    # Subsets
    # SubstituteComponent
    # SubstitutionMode
    # SuppressComponents
    # SuppressedState
    # Tag
    # UnsuppressComponents
    pass