from NXOpen import DisplayableObject


class Component(DisplayableObject):
    # AttributeInformation
    # AttributeType
    # Blank
    # CollaborativeContentType
    # Color
    # ComputationalTime
    # CreateAttributeIterator
    # CreateEmptyPartFamilyInstanceSelectionCriteria
    # DateAndTimeFormat
    # DeleteAllAttributesByType
    # DeleteAttributeByTypeAndTitle
    # DeleteCharacterstics
    # DeleteInstanceUserAttribute
    # DeleteInstanceUserAttributes
    # DeletePartFamilyInstanceSelectionCriteria
    # DeleteUserAttribute
    # DeleteUserAttributes
    # DesignElementRevision
    # DesignSubordinateRevision
    # DirectOwner
    # DisplayComponentsExact
    # DisplayComponentsLightweight
    # DisplayName
    # EmptyPartRefsetName
    # EntirePartRefsetName
    # EstablishIsolatedPositionOverride
    # EstablishPositionOverride
    # FindComponentPatterns
    # FindObject
    # FindOccurrence
    # FixConstraint
    # GetArrangements
    # GetAsRequiredQuantity
    # GetAttributeTitlesByType
    # GetBooleanUserAttribute
    # GetCharacteristics
    # GetChildren
    # GetComponentQuantityType
    # GetComponentRepresentationMode
    # GetComputationalTimeUserAttribute
    # GetConstraints
    # GetDegreesOfFreedom
    # GetDestinationCharacteristics
    # GetInstanceBooleanUserAttribute
    # GetInstanceIntegerUserAttribute
    # GetInstanceRealUserAttribute
    # GetInstanceStringUserAttribute
    # GetInstanceTimeUserAttribute
    # GetInstanceUserAttribute
    # GetInstanceUserAttributeAsString
    # GetInstanceUserAttributeLock
    # GetInstanceUserAttributes
    # GetInstanceUserAttributesAsStrings
    # GetIntegerAttribute
    # GetIntegerCharacteristic
    # GetIntegerQuantity
    # GetIntegerUserAttribute
    # GetLayerOption
    # GetNextUserAttribute
    # GetNonGeometricState
    # GetPartFamilyInstanceSelectionCriteria
    # GetPdmReferenceAttributeValue
    # GetPosition
    # GetPositionOverrideParent
    # GetPositionOverrideType
    # GetRealAttribute
    # GetRealCharacteristic
    # GetRealQuantity
    # GetRealUserAttribute
    # GetReferenceAttribute
    # GetStringAttribute
    # GetStringCharacteristic
    # GetStringUserAttribute
    # GetTimeAttribute
    # GetTimeUserAttribute
    # GetUserAttribute
    # GetUserAttributeAsString
    # GetUserAttributeCount
    # GetUserAttributeLock
    # GetUserAttributeSize
    # GetUserAttributeSourceObjects
    # GetUserAttributes
    # GetUserAttributesAsStrings
    # HasInstanceUserAttribute
    # HasUserAttribute
    # Highlight
    # IsBlanked
    # IsFixed
    # IsOccurrence
    # IsPositioningIsolated
    # IsSuppressed
    # JournalIdentifier
    # Layer
    # LineFont
    # LineWidth
    # ModelElementRevision
    # Name
    # NameLocation
    # Null
    # ObjectFont
    # ObjectWidth
    # OwningComponent
    # OwningPart
    # Parent
    # Print
    # Prototype
    # RecallAndListConstraints
    # RecallConstraints
    # RedisplayObject
    # ReferenceSet
    # RemovePositionOverride
    # RemoveRememberedConstraints
    # RemoveViewDependency
    # RepresentationMode
    # SetAttribute
    # SetBooleanUserAttribute
    # SetCharacteristic
    # SetCharacteristic2
    # SetCharacteristics
    # SetCharacteristics2
    # SetInstanceBooleanUserAttribute
    # SetInstanceTimeUserAttribute
    # SetInstanceUserAttribute
    # SetInstanceUserAttributeLock
    # SetLayerOption
    # SetName
    # SetNameLocation
    # SetPartFamilyInstanceSelectionCriteria
    # SetPdmReferenceAttribute
    # SetPositioningIsolated
    # SetPositioningVaried
    # SetReferenceAttribute
    # SetTimeAttribute
    # SetTimeUserAttribute
    # SetUsedArrangement
    # SetUserAttribute
    # SetUserAttributeLock
    # Subset
    # Suppress
    # SuppressingArrangement
    # Tag
    # Unblank
    # Unhighlight
    # Unsuppress
    # UpdateStructure
    # UsedArrangement
    @property
    def DisplayName(self)->str:
        pass

